name: Build and test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Unset JAVA_HOME
        run: unset JAVA_HOME
      - uses: asdf-vm/actions/install@v1
      - name: Check
        run: ./gradlew check
